//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.16 at 02:12:58 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.oorsprong.org/websamples.countryinfo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.ws.CountryWs;
